#include "Convolution.cu"
#include "GraphSpread.cu"
#include "gravitational_predictions.cu"
#include "mandelbrot.cu"
// TODO ci_productions #include "mandelbrot3d.cu"
#include "overlay_underlay.cu"
#include "PendulumFractal.cu"
#include "render_3d_points_lines.cu"
#include "SurfaceRenderer.cu"
#include "ComplexPolynomial.cu"
#include "root_fractal.cu"
#include "cuda_graphics.cu"
//#include "Conway.cu"

