void render_video() {
    stage_macroblock(FileBlock("Hit a billiards ball,"), 1);
    stage_macroblock(FileBlock("and it reflects off of the walls before continuing on its path."), 1);
    stage_macroblock(FileBlock("This is _inner_ Billiards."), 1);
    stage_macroblock(FileBlock("Its path might look interesting,"), 1);
    stage_macroblock(FileBlock("but I want to show you _outer_ billiards."), 1);
    stage_macroblock(FileBlock("The ball is hit so as to just graze the edge of the wall."), 1);
    stage_macroblock(FileBlock("going twice the length of the point of contact."), 1);
    stage_macroblock(FileBlock("We continue by hitting it again to graze the next corner of the table."), 1);
    stage_macroblock(FileBlock("Keep doing this, and we get a very nice pattern."), 1);
    stage_macroblock(FileBlock("This ball, under these rules, will go in an infinite cycle of 8 positions."), 1);
    stage_macroblock(FileBlock("Move it slightly, and it is instead trapped in a non-repeating loop."), 1);
    stage_macroblock(FileBlock("This position is not part of a closed, finite cycle."), 1);
    stage_macroblock(FileBlock("Instead, its trajectory lands on infinitely many different points."), 1);
    stage_macroblock(FileBlock("The rules of this game are conveniently invertible:"), 1);
    stage_macroblock(FileBlock("we can play the game in reverse and recover what points lie on this infinite chain before our starting point."), 1);
    stage_macroblock(FileBlock("What separates a finite cycle from an infinite chain?"), 1);
    stage_macroblock(FileBlock("Let's see what happens when starting from each point."), 1);
    stage_macroblock(FileBlock("From each position, start playing outer billiards."), 1);
    stage_macroblock(FileBlock("Run the game for 1000 iterations."), 1);
    stage_macroblock(FileBlock("Check how close the ball gets to its origin within those iterations."), 1);
    stage_macroblock(FileBlock("That'll be the brightness of the pixel."), 1);
    stage_macroblock(FileBlock("Also, we'll keep track of how many iterations it took to make that close approach,"), 1);
    stage_macroblock(FileBlock("and document it as the color of the pixel."), 1);
    stage_macroblock(FileBlock("Now, we can see that the smallest cycle has length 4."), 1);
    stage_macroblock(FileBlock("Here's cycles of lengths 5..."), 1);
    stage_macroblock(FileBlock("6..."), 1);
    stage_macroblock(FileBlock("29..."), 1);
    stage_macroblock(FileBlock("Wow. Lots of interesting cycles."), 1);
    stage_macroblock(FileBlock("We can even investigate what happens if the table shape is different."), 1);
    stage_macroblock(FileBlock("But there's one issue here..."), 1);
    stage_macroblock(FileBlock("What happens when a ball is right on the edge?"), 1);
    stage_macroblock(FileBlock("We know what direction to hit it to just graze the table,"), 1);
    stage_macroblock(FileBlock("and I _guess_ we could just hit it to mirror across the midpoint of that side of the table..."), 1);
    stage_macroblock(FileBlock("But with arbitrarily-shaped tables,"), 1);
    stage_macroblock(FileBlock("that stops making much sense."), 1);
    stage_macroblock(FileBlock("If this is our table,"), 1);
    stage_macroblock(FileBlock("then where's the midpoint?"), 1);
    stage_macroblock(FileBlock("New rule: a ball has to graze the corner of the table."), 1);
    stage_macroblock(FileBlock("None of this edge-parallel funny business."), 1);
    stage_macroblock(FileBlock("So if a ball starts right on this line, then it is no longer in play."), 1);
    stage_macroblock(FileBlock("Same for these other lines, corresponding to the other table edges."), 1);
    stage_macroblock(FileBlock("What if the ball starts on this line?"), 1);
    stage_macroblock(FileBlock("Still no good- we can hit it once, but then it lands on the _other line_..."), 1);
    stage_macroblock(FileBlock("One move delayed, sure, but it will still be forced to graze the wall."), 1);
    stage_macroblock(FileBlock("Let's color the lines to show how many moves a ball can last before crashing into a wall."), 1);
    stage_macroblock(FileBlock("1 move,"), 1);
    stage_macroblock(FileBlock("2,"), 1);
    stage_macroblock(FileBlock("3..."), 1);

    stage_macroblock(FileBlock("Ok. This is very cool. But what about the areas which are not caught in the singularity?"), 1);
    stage_macroblock(FileBlock("Let's take this section as a case study."), 1);
    stage_macroblock(FileBlock("Placing a lot of balls in it,"), 1);
    stage_macroblock(FileBlock("we can see that they all fall right into the next section over."), 1);
    stage_macroblock(FileBlock("This makes some intuitive sense when we look back at our cycle graph:"), 1);
    stage_macroblock(FileBlock("right at the center of each of them, we see a cycle of length 4."), 1);
    stage_macroblock(FileBlock("Let's color these regions."), 1);
    stage_macroblock(FileBlock("Darker means."), 1);
    stage_macroblock(FileBlock(""), 1);
    stage_macroblock(FileBlock(""), 1);
    stage_macroblock(FileBlock("One last treat: what happens if, instead of playing in euclidean space,"), 1);
    stage_macroblock(FileBlock("we play it in hyperbolic geometry?"), 1);
}
